openapi: "3.0.3"
info:
  title: Reversi Web App
  version: "1.0.0"

paths:
  /api/games:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  games:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        winnerDisc:
                          type: integer
                          example: 1
                        startedAt:
                          type: string
                          format: date-time
                          example: "2024-01-01T12:00:00Z"
    post:
      responses:
        201:
          description: Game created
  /api/games/latest/turns/{turnCount}:
    parameters:
      - name: turnCount
        in: path
        required: true
        schema:
          type: integer
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: integer
                example: 1
                properties:
                  board:
                    type: array
                    example:
                      - [0, 0, 0, 0, 0, 0, 0, 0]
                      - [0, 0, 0, 0, 0, 0, 0, 0]
                      - [0, 0, 0, 0, 0, 0, 0, 0]
                      - [0, 0, 0, 1, -1, 0, 0, 0]
                      - [0, 0, 0, -1, 1, 0, 0, 0]
                      - [0, 0, 0, 0, 0, 0, 0, 0]
                      - [0, 0, 0, 0, 0, 0, 0, 0]
                      - [0, 0, 0, 0, 0, 0, 0, 0]
                  nextDisc:
                    type: integer
                    example: 1
                  winnerDisc:
                    type: integer
                    example: 1
  /api/games/latest/turns/:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                turnCount:
                  type: integer
                  example: 1
                move:
                  type: object
                  properties:
                    disc:
                      type: integer
                      example: 1
                    x:
                      type: integer
                      example: 1
                    y:
                      type: integer
                      example: 1
      responses:
        201:
          description: Created
